### ISSUE TITLE
funty crate crashes the compiler: rustc panicked at 'Multi-register value not expected'

### ISSUE THREAD

**Issue by fredericp** [bjorn3/rustc_codegen_cranelift#1150] opened 2021-03-16 19:32 UTC
The crate [funty](https://github.com/myrrlyn/funty/blob/master/src/lib.rs) crashes the compiler.

Steps to reproduce:
1. Download and install rustc_codegen_cranelift. I used [this compilation](https://github.com/bjorn3/rustc_codegen_cranelift/actions/runs/654334077)
1. `git clone git@github.com:myrrlyn/funty.git`
1. `cd funty`
1. `cargo.sh test`

Error message:

```
cargo.sh test
    Updating crates.io index
   Compiling static_assertions v1.1.0
   Compiling funty v1.2.0 (/home/frede/Projectes/funty)
thread 'rustc' panicked at 'Multi-register value not expected', /home/runner/.cargo/git/checkouts/wasmtime-41807828cb3a7a7e/df6812b/cranelift/codegen/src/isa/x64/lower.rs:128:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-nightly (8f349be27 2021-03-08) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
Instance { def: Item(WithOptConstParam { did: DefId(2:19423 ~ core[8231]::num::{impl#4}::rotate_left), const_param_did: None }), substs: [] } _ZN4core3num22_$LT$impl$u20$i128$GT$11rotate_left17hfe9b83548de0c2caE
error: could not compile `funty`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by bjorn3** [comment] 2021-03-16 19:59
Duplicate of https://github.com/bjorn3/rustc_codegen_cranelift/issues/1114

**Closed by bjorn3** 2021-03-16 19:59 UTC
